export const GET_USERS = "GET_USERS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const POST_USER = "POST_USER";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const ORDERPHONE = "ORDERPHONE";
export const FILTERPHONE = "FILTERPHONE"
